### ISSUE TITLE
Exec Team Meeting (2023-06-13)

### ISSUE THREAD

**Issue by dgkf** [pharmaR/pharmaR#15]
### Agenda

- Recap action items from #7 
- Discuss any prep work needed leading up to https://github.com/pharmaR/events/issues/10
- Workstream roundtable updates

**Comment by jmanitz** [comment]
Please review and edit the draft slides for the meeting
https://github.com/pharmaR/events/tree/main/community_meetings/2023-06-27

**Comment by emilliman5** [comment]
### Attendees:

Doug Kelkhoff (Chair/Repository lead, Roche)
Eric Milliman (Biogen/riskmetric lead)
Aaron Clark (Biogen/ R Shiny App lead)
Juliane Manitz (Merck Serono/ Comms lead)
Joe Rickert (R Consortium/R Studio)
Preetham Palukuru (Merck)

### Discussion

#### Blogging responsibilities

- Discussed everyone contributing to blogposts, especially if someone had direct involvement with the topic of the post. We want to encourage more engagement with communicating successes/topics etc. 
- @dgkf mentioned working to further reduce the admin overhead to publishing to PharmaR site

#### Discussed growing the communications workstream: 

- Doug has posted internally at Roche, Eric announced to the riskmetric team. 
- Possibly creating quarto/xaringan theme for presentations as code, and lessening burden while increasing reach.
- [x] @dgkf to add slide introducing lead role turnover in RValHub as well as a call for volunteers for exec and comms WS.

#### Prep work for all-hands:

- [x] @AARON-CLARK volunteered to port current all-hands slides to xaringan so that team can collaborate via github. Discussion rounds will have ~10 minutes. Each discussion leader can create a few slides to help drive discussion. 

#### General events organizing feedback

- Discussed new structure in github for events. Top-level issue with subtasks that can be individually assigned however, requires more admin work to create and manage many separate tasks.

#### Workstream round table updates:

##### riskassessment/riskmetric

- Discussing/planning goals for the next year. https://github.com/pharmaR/riskmetric/issues/298 
- Merck has successfully integrated riskmetric into their package validation workflow. :tada: 
- Opportunity to present best practices on reproducible testing as a way to engage enterprise users to adopt and contribute back to projects

##### repositories WG

- Completed stakeholder interviews complete
- Weekly ideation phase (4 weeks)
- Reengaging users to PoC/test solutions
- unrealistic to have one repository for packages to reside that are tested to everyone's liking/requirement -> next best option is to consistently test and document packages and communicate that back to maintainers or contribute code to get package to meet some set of basic requirements

**Comment by dgkf** [comment]
@AARON-CLARK, others - adding a link to the mentioned [repositories workstream ideation contributions](
https://drive.google.com/drive/folders/1UWwNN9pxU__6kfmDvACSLPr8BdorP_4W). You might need to request access, but either myself or @Crosita will be happy to grant you access.

**Comment by dgkf** [comment]
And another follow-up from me to share the internal posting I made for our Communications Workstream. Small tweaks to adapt some internal-specific stuff.

We have an internal opportunities board and I posted this requesting 10% time.

> Participate in the R Validation Hub as a member of the new communications workstream.
> 
> The R Validation Hub is an external, cross-pharma group formed with the purpose of bolstering the use of R in a regulated industry context. We work to recommend processes, provide tools and host knowledge sharing sessions as an open forum for communication. Learn more at www.pharmar.org.
> 
> We've recently taken a pulse check of our team, and identified communication as a key area that we want to improve. For this we're looking to grow a team of new participants. To keep the spirit of being cross-pharma, we're looking for participants that span a few organizations who can help to coordinate events, improve our webpage, write blog posts and standardize the way we share presentation materials.
> 
> Depending on your interests, this role can be either focusing on industry networking, soft skills or technical skills:
> 
> Soft Skills:
> - Grow your network with related R working groups, including ROpenSci, the R Consortium (and other working groups within the R Consortium), PSI/AIMS and PHUSE
> - Learn more about the state of using R in regulated spaces, growing awareness for where key challenges lie and how other companies are addressing them
> - Build experience with open (or open-source) project organizing and maintenance, using GitHub's issue trackers and project boards to track activities
> 
> Technical Skills:
> - Using static webpage generators to rebuild our website (we've been interested in a rewrite using quarto)
> - Enhancing our CI/CD to keep our webpage more up-to-date
> - Building a quarto extension to theme slides so that we can version control our various presentations as code

**Comment by AARON-CLARK** [comment]
Thanks @dgkf. I used this template within my org 👍🏼
