### ISSUE TITLE
Proposal: add repo for new package containing `riskmetric` scored CRAN data

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/pharmaR#19]
Since scoring CRAN and presenting a small preview of that data at our latest all-hands community meeting, there has been interested from other orgs to digest that data. @dgkf & @emilliman5 decided it might be nice to create an R package that just contains all the `{riskmetric}` scored CRAN data and updating it on a regular cadence (like once a year) to identify trends.

The current process of scoring CRAN was composed by @AARON-CLARK & is being reviewed by Eric. Once "approved", I'm sure we could upload the script that generates that data into the `inst/` folder of the R package itself, so users get it bundled with their pkg installation, in case they want to make some tweaks.

FYI - Aaron's current script is about 10MB but keeps the pkg_ref object. We should strip that out (as well as other unneeded columns) and probably see much smaller file sizes.

**Comment by dgkf** [comment]
I think this would be an awesome contribution. Just off the top of my head, I think it would support:

- More effective discussion about how to summarize risk
- Communicating changes to the summarizing algorithm or interpretations of assessment data
- Distributing tools for building datasets (ie, pointing to a private repo instead of CRAN, but reusing the same script to compare internal and external packages)
- Allowing us to report risk scores in terms of "CRAN percentile" instead of just some arbitrary numeric value.

I would probably even tuck the function for generating the data into the package itself. The only concern would be that post-processing of the dataset might be specific to the version of `riskmetric` used, so I can see it evolving into a web of `if (packageVersion("riskmetric") > ...)` statements. Regardless, I'd say we can cross that bridge when we get there. Having a function that people can use today to assess a full repo of packages is too valuable.

edit: if we want to commit to this as a path forward, let me know what repo name you'd want and I can kick it off for you

**Comment by emilliman5** [comment]
I like this idea and think we should move it forward. Another benefit to this resource is the identification of edge cases, and inconsistencies in riskmetric workflow.

Possible repo names:
riskmetric.scores
riskmetric.cranscores (incase we want a riskmetric.biocscores)
risk.scores
riskscores

In this repository, I propose the following elements:
1) data.frame of summarized risk scores and metrics
2) data.frame of package assessments (if space permits, this would allow even better comparison of changes to scoring changes)
3) code to generate and store this data (I am working on a parallel execution) we 

@AARON-CLARK's analysis dataset is good to share with those that have expressed interest, but I think we should hold off on posting it as the first version until we take some time to design the results data and repo so that we capture all of the necessary metadata for each version of the analysis.

I propose we update the data bi-annually, and/or with every new release of riskmetric

**Comment by AARON-CLARK** [comment]
> Allowing us to report risk scores in terms of "CRAN percentile" instead of just some arbitrary numeric value.

👍🏼 I love that idea for the {riskassessment} app

> Possible repo names:
> riskmetric.scores

👍🏼 I like any of those repo names, but I think I'd lean more heavily towards `riskmetric.scores`. If space permits, it would be nice to fit both bioconductor and cran scores in one package, but perhaps two different sets of data.frames.

> data.frame of package assessments

👍🏼 I second this!

> I propose we update the data bi-annually and/or with every new release of `riskmetric`

👍🏼 I definitely second this. I'd propose doing both!

We've encountered issues with the {riskassessment} app failing to connect to certain URLs when compiling info for the database... In that event, we do some error handling. However, if we prompt the user, we could potentially fall back on the new repo's assessments & scores. Similarly, we could show a trend of scores over time without requiring the app's user to re-assess the package on a regular basis to create that data in the database.

I could this source of data becoming a way in which folks build `riskmetric` badges for their package READMEs too.

**Comment by dgkf** [comment]
As an analog to `riskmetric`, I think I'm partial to `riskscore` - Both are succinct, and oddly singular. 

The lack of a plural "metrics" always stood out to me, but I say we lean in to it and make it our brand. `riskmetric.scores` feels _okay_, but package names with `.` still feel weird to me, even as a veteran of the language. Especially when I was newer to R, seeing `<package>.<??>::<function>` always felt a bit inaccessible, like I'm missing some fundamental syntax (turns out R is just weird). 

There's an existing `riskScorescvd` (for cardiovascular risk scores), but I think they're different enough that the name similarity wouldn't be an issue.

**Comment by emilliman5** [comment]
i'm on board with `riskscore`

**Comment by AARON-CLARK** [comment]
@dgkf, `riskscore` sounds good 👍🏼

**Comment by dgkf** [comment]
Alright! New repository is kicked off at https://github.com/pharmaR/riskscore
