### ISSUE TITLE
Exec Team Meeting (2023/07/11)

### ISSUE THREAD

**Issue by dgkf** [pharmaR/pharmaR#21]
#### Recap

* Community meeting (06/27) - recording available?
* [New event planning workflow retrospective](https://github.com/pharmaR/events/issues/26): what worked well, what needs improvement for next time?

#### Planning

* Kicked off event planning for [2-part seminar series on `{riskmetric}` and `{riskassessment}`](https://github.com/orgs/pharmaR/projects/7/views/1?filterQuery=milestone%3A%22All+Hands+%282023-08-09%2C16%29%22+is%3Aopen+) (08/09 & 08/16)

#### Knowledge Sharing

* Follow-up Strategic WS: Suggestion to lean on _Pharma Oversight Committee_ within R Consortium or _Programming Head Counsil_ (ad hoc, cross-pharma forum for statistical/data science/analyst leadership)
* [R Validation Hub quarto](https://github.com/pharmaR/rvalhub-quarto)
* Round table updates

**Comment by emilliman5** [comment]
Notes:

### Recap:

* Community meeting take aways: 
  * Good discussion on use of data for testing r packages
  * There is a link to the recording internally
     * Juliane can enable access to individuals. 
     * Need to download and host to make it publicly available. 
     * Doug to follow up with R Consortium to host on YouTube (Contact is Jesse from Story Changes Culture) (task included below)
- [x] Discussed moving blog posts to R/Consortium webpage or cross posing blogs posts. @dgkf to kick off discussion (first pass: continue duplicating posts, look to embed/redirect to R Consortium posts with website rework)
* Event planning retrospective discussion
   * Pro: Assign people to specific tasks to ensure someone is responsible
   * Con: Way too many notifications
   * **Action:** For future events, person that will be leading/presenting will be responsible for initiating the events tasks template, choose what level of organization they feel is necessary for the event (just checkbox list vs individual issues that can be assigned out)

### Planning

- [x] Write one abstract that encompasses both talks. Once final reply to GH issue. (@dgkf to assign eric and aaron to the issue as to not duplicate tasks here)
- [x] @dgkf to reach out to R Consortium after abstract is prepped, including: 
   - Request R/Consortium to create zoom webinars for riskmetric and riskassessment talks.
   - Include LinkedIn in for advertising media blitz. Doug will remind exec team to promote to individual networks.
   - Send off previous recording for upload to R Consortium YouTube channel (Juliane went ahead and started coordinating with SCC)

### Knowledge Sharing:

- Pharma Oversight Committee: 1 delegate from every pharma R/Consortium member. JR would provide updates on current workstreams, educated members on fee earmarking, and keep members informed of projects.
- Instead of creating a strategic workstream we will leverage the Pharma Oversight Committee. Will work to get a standing invite to provide updates
- Programming Head Counsel is __ad hoc__ but is potentially composed of very senior leaders withinin Stat Programming orgs of various pharma companies. Meetings are not publicly posted. Ony composed of big pharma, no CROs or start-ups included in Counsel. For this reason, we prefer the Pharma Oversight Committee.
- When presenting to these strategic groups, invites to CRO and startup stakeholders to ensure their opinions are heard and that they remain abreast of RVH's strategy
- Instead of going to Pharma Oversight committee we hold a strategy session and invite relevant stakeholders hoping to leverage mailing lists of these key groups.
- Doug has created a quarto theme for slides as code for presentations. Can we make the addition of the theme point and clickable (https://github.com/pharmaR/rvalhub-quarto/issues/1)?

_edited by @dgkf with minor formatting and to add my own notes_

**Comment by AARON-CLARK** [comment]
> * When presenting to these strategic groups, invites to CRO and startup stakeholders to ensure their opinions are heard and that they remain abreast of RVH's strategy
> * Instead of going to Pharma Oversight committee we hold a strategy session and invite relevant stakeholders hoping to leverage mailing lists of these key groups.

Hi, I should have clarified at our meeting, but I have two interested parties in the hopper (from BMS & Biogen) who were interested in contributing to the "strategic" workstream before we settled on leveraging the Pharma Oversight Committee. Reading the two bullet points above, should I assume they can still be invited to these sessions, or should I tell them the opportunity is no longer available? I'm fine with it either way. Thanks!

**Comment by AARON-CLARK** [comment]
Any comments on this? Perhaps @dgkf? Thanks!

**Comment by dgkf** [comment]
> Any comments on this? Perhaps @dgkf? Thanks!

Thanks @AARON-CLARK for the extra ping. The decision at the last meeting was to leverage these groups instead. 

Please pass on my apologies as we'll no longer be looking for additional participants - responsibility definitely falls on my shoulders for not having the awareness of these groups from the start. 

I know Biogen is already a platinum sponsor of the R Consortium, so I believe they should already have a representative on the Oversight Committee. BMS doesn't appear to be a sponsor. Although we do want to keep the door open for guests, our initial thinking was that we want that opportunity to go to underrepresented parts of the industry (namely small-scale pharmas/CROs/academics), and I'd feel uncomfortable using this path for a company as large as BMS - involvement would probably have to come through a R Consortium sponsorship.

Thanks again for seeking them out in the first place, and sorry for landing you in the uncomfortable position of having to tell them we've changed course.
